### ISSUE TITLE
assertion failed on Windows

### ISSUE THREAD

**Issue by AlexOnWork** [ocsigen/lwt#390] opened 2017-06-07 10:47 UTC
Sometimes our Windows app (using lwt 2.7.1) crashes with following message:
> Fatal error: exception File "src/core/lwt.ml", line 511, characters 8-14: Assertion failed

I'm enabled stacktraces and rebuilt app with lwt 3.0.0 and now waiting for a problem to happen again; what also can I do to find a reason of this error?

**Comment by aantron** [comment] 2017-06-07 15:31
Thanks for reporting this. It looks like a potential duplicate of https://github.com/ocsigen/lwt/issues/349#issue-227673438, but we can't be sure because we haven't debugged either one yet (:/).

Enabling stack traces is the right thing to do first. See if you get a similar one to the linked issue. I would also suggest noting whatever steps are needed to reproduce this (commit of your code, environment, setup, etc).

Ultimately, I think we will have to instrument the code in `lwt.ml` to some degree, and hope that we can reproduce the failure with the instrumented code.

Is your code open source? If not, would you be willing to give temporary access to an Lwt maintainer, to try to track down the issue? Do you want to fix this ASAP, or is it okay to delay a little?

My current plan for these kinds of issues is to fix them one at a time, since fixing one might turn out to fix several. See the new [stability project](https://github.com/ocsigen/lwt/projects/1) for the queue. However, I'm happy to adjust this with your constraints in mind.

cc @domsj @copy

**Comment by AlexOnWork** [comment] 2017-06-08 12:38
Hi @aantron, thanks for your reply.
After updating to 3.0.0 we have got this trace:

> Fatal error: exception "Assert_failure src/core/lwt.ml:511:8"
Raised at file "src/core/lwt.ml", line 511, characters 8-20
Called from file "src/core/lwt.ml", line 202, characters 8-15
Called from file "src/core/lwt.ml", line 202, characters 8-15
Called from file "src/core/lwt.ml", line 202, characters 8-15
(last line repeated lots of time)

Also sometimes it segfaults with backtrace pointing to some of OCaml code; I'm not sure if this two problems are related as we have some C stubs; but it crashes even when C code is not called at all during app execution.
Unfortunately our app is proprietary; we are using lots of Lwt_process functions, file IO and mvars; I'm not sure if I can isolate problem to some minimal example.
Any suggestions of what can we do to help you debugging this crash?

**Comment by aantron** [comment] 2017-06-08 15:01
> After updating to 3.0.0

I guess one way we could start looking for this is by:

- Pinning all your OPAM dependencies to fixed versions, the current ones being installed when you build.
- As a control, pinning Lwt to 3.0.0 and confirming the crash is there. I guess this step can be skipped, but it's useful for sanity :)
- Pinning Lwt to 2.7.1, which should be largely identical to 3.0.0. The two versions were tagged days apart, and they should differ only in that 3.0.0 committed some breaking changes, mostly API and package renamings. 2.7.1 and 3.0.0 should otherwise have the same internal logic. Does the app still crash with 2.7.1?
- Pinning Lwt to 2.7.0. Does it still crash with 2.7.0?
- This might take a few iterations, in case current versions of some dependencies and/or the app can't build with all these versions of Lwt. Hopefully, there is a stable set of dependencies, and we won't have to modify or patch anything to be able to do this.

If, this way, it looks like Lwt 3.0.0 (or some other version) is what introduced the problem, then perhaps we can proceed by grepping through your code base (and maybe dependencies, but not sure if that will be necessary) for all instances of a call to an Lwt API. We can try to look at what changed between the last version of Lwt that did not have this problem and 3.0.0, and see if it's related to any of the APIs being used.

I think, during these runs, we should try to avoid calling any C stubs beyond those that are in dependencies (such as Lwt itself).

**Comment by AlexOnWork** [comment] 2017-06-08 17:10
Possibly related to https://github.com/ocsigen/lwt/issues/315 , I'm getting the same stacktrace.
I tried Lwt 3.0.0, 2.7.1 and 2.5.2 - all of them have this problem.
I can't use earlier versions as it requires older OCaml compiler while we are using some of 4.03 features.
Also I can't reproduce this problem at Linux and OS X - though the code is a little different on this platforms.

**Comment by aantron** [comment] 2017-06-08 18:13
Argh, well there goes my whole strategy :) thanks for testing that.

I'm thinking about what to do next. In the meantime, I have never tried this, but there is the possibility that the Lwt tracing branch by @talex5 might help to see what's happening: https://github.com/mirage/lwt/tree/tracing

Here's an introduction to it: http://roscidus.com/blog/blog/2014/10/27/visualising-an-asynchronous-monad/

The current instructions, AFAIK, are:

- https://github.com/mirage/mirage-profile#recording-traces-manually, see the first paragraph for pinning, and the last paragraph for tracing Unix processes (in this context, I believe Unix includes Windows :)).
- https://github.com/mirage/mirage-profile#viewing-traces for viewing the trace.

**Comment by aantron** [comment] 2017-06-30 23:36
Just want to follow up in this issue also, so it doesn't look like we abandoned it – see @copy's [link](https://github.com/ocsigen/lwt/issues/315#issuecomment-310931104) about the Skylake CPU bug. This CPU bug explained all similar issues reported on Lwt. Let us know if you are observing this on a non-Skylake non-Kaby-Lake CPU, or microcode updates don't resolve the issue.

**Comment by aantron** [comment] 2017-06-30 23:36
(I have no idea how GitHub mangled the comment above).

**Comment by AlexOnWork** [comment] 2017-07-02 18:02
@aantron At some point I'm just replaced Lwt with our own (very basic) replacement which solved the problem.
I can't confirm that our customer experiencing this bug was using Kaby Lake/Skylake CPU - but I never seen this bug on oldest CPUs which we use in our lab.
Anyway, thank you for your work on Lwt!

**Comment by aantron** [comment] 2017-07-02 18:06
Thanks for the response. I will close this issue; but please comment and/or reopen if you get more information, it comes up again, etc. :)

You "may" still want to bug your customer more about the CPU, because this crash occurs in OCaml code that is not using Lwt, as well (but you know best!).

**Closed by aantron** 2017-07-02 18:06 UTC
Labels: difficult
