### ISSUE TITLE
High memory usage when using Lwt_unix.with_timeout

### ISSUE THREAD

**Issue by ryanslade** [ocsigen/lwt#670] opened 2019-02-26 17:06 UTC
I've noticed that when using `Lwt_unix.with_timeout` I see a massive increase in the amount of memory used by my program. My assumption is that the timeout promises are not being cancelled properly.

I'm using Lwt version 4.1.0

The issue can be reproduced in the following way:

Start a nc session using `nc -l 8080`

Run the following program

```ocaml
open Lwt

let port = 8080

let writer timeout = 
  let host = Unix.inet_addr_of_string "127.0.0.1" in
  let addr = Unix.ADDR_INET(host, port) in
  Lwt_io.open_connection addr 
  >>= fun (_,oc) ->
  let rec write_loop () =
    (if timeout > 0.0
     then
       Lwt_unix.with_timeout timeout (fun () -> Lwt_io.write oc "Hello")
     else
       Lwt_io.write oc "Hello")
    >>= fun () ->
    write_loop ()
  in
  write_loop ()

let () =
  Lwt_main.run (writer 1.0)

```

Notice that the amount of memory used by the program spikes and grows rapidly.

If the same program is run with a timeout of 0.0, memory usage stays low and does no increase.

**Comment by aantron** [comment] 2019-02-26 23:31
It's possible that the timeout promises are being canceled, just a garbage collection cycle hasn't yet occurred. What happens if you insert a call to `Gc.full_major ()` every N iterations for some N?

**Comment by aantron** [comment] 2019-02-26 23:42
Confirmed. Inserting `Gc.full_major` fixed the problem here. So, the promises are indeed being canceled, but the program allocates a very large number of them, and they are not being deallocated because the program does not need to reclaim the memory yet.

I recommend either manually inserting a `Gc.full_major` call every N iterations, or wrapping much larger operations (sequences of them) in `Lwt_unix.with_timeout`, or accepting this memory usage, or limiting the heap size manually if this process is not playing well with the rest of your system.

**Comment by ryanslade** [comment] 2019-02-27 08:21
I tried inserting `Gc.full_major ()` every 100,000 iterations and all it did was slow down the program but memory usage continued to grow (at a slower rate).

I grabbed `Gc.counters` before and after each GC run and this is what I saw:
```
Before GC          
Minor 25629131.000000 Promoted 3797850.000000 Major 3798902.000000
After GC
Minor 25629276.000000 Promoted 3808189.000000 Major 3809241.000000

Before GC
Minor 51245999.000000 Promoted 7602861.000000 Major 7603913.000000
After GC
Minor 51246144.000000 Promoted 7611371.000000 Major 7612423.000000

Before GC
Minor 76862877.000000 Promoted 11406063.000000 Major 11407115.000000
After GC
Minor 76863022.000000 Promoted 11414573.000000 Major 11415625.000000

Before GC
Minor 102479717.000000 Promoted 15189788.000000 Major 15190840.000000
After GC
Minor 102479863.000000 Promoted 15217743.000000 Major 15218795.000000

Before GC
Minor 128096613.000000 Promoted 18992880.000000 Major 18993932.000000
After GC
Minor 128096759.000000 Promoted 19020851.000000 Major 19021903.000000

Before GC
Minor 153713506.000000 Promoted 22795978.000000 Major 22797030.000000
After GC
Minor 153713652.000000 Promoted 22823953.000000 Major 22825005.000000

Before GC
Minor 179330376.000000 Promoted 26599120.000000 Major 26600172.000000
After GC
Minor 179330522.000000 Promoted 26627095.000000 Major 26628147.000000
```

**Comment by aantron** [comment] 2019-03-06 17:28
It looks like you may instead need to insert a call to `Lwt.pause ()` (with a bind on its result) every N iterations. That seems to have solved it for me.

Here is a description of what is (most likely) happening:

1. When Lwt is asked to do a `write`, it first tries to do the `write` immediately. If that succeeds, the `write` promise is resolved, and its callbacks are called immediately. If the `write` fails with `EAGAIN`/`EWOULDBLOCK`, Lwt "remembers" that it needs to poll the fd for writability the next time it is calling `select`/`epoll`/`kqueue`/whatever. The `write` promise is pending, and its callbacks are deferred until at least the next `select`.

    Your write is always succeeding immediately, because of the connection to netcat on localhost. So, the callback is called immediately, continuing the loop to the next `write`, on the CPU, without ever getting into `select`.

2. Lwt can only become aware that an `Lwt_unix.sleep` has expired at the same time it does a `select`. All the I/O polling and timeout logic are built into that `select` I/O loop.

    Because this program never has to "resort" to `select`, Lwt never becomes aware of any timeouts expiring, so these `Lwt_unix.sleep` promises (used internally by `Lwt_unix.with_timeout`) never become resolved. Instead, they accumulate in a queue of promises Lwt is supposed to check when it finally gets a chance to do `select`, which it never does. This is the source of the memory leak.

The solution is to insert an `Lwt.pause () >>= fun () ->` into your loop, perhaps done every N iterations. `Lwt.pause ()` is a promise that is resolved only *after* Lwt has had a chance to do its call to `select`.

**Comment by aantron** [comment] 2019-03-06 17:31
I think the reason I "saw" `Gc.full_major` "solve" the problem before is that I was doing collections too frequently (N too small), so that the program was running slowly enough to hide the heap growth.

**Comment by ryanslade** [comment] 2019-03-07 15:25
Thanks for your detailed response, appreciate it.

I can confirm that this has indeed fixed the issue in the example program above.

Unfortunately it doesn't seem to have fixed the issue I'm seeing in my "real world" program so I'll need to try and find another example that more clearly reproduces the issue. Strangely in my program I'm seeing a positive correlation between the timeout value I use and the speed of memory growth. I'm also testing against localhost and in my tests I never actually time out.

**Comment by aantron** [comment] 2019-04-03 08:48
Going to close this until further info, please reopen if you are able to pinpoint this more closely :)

**Closed by aantron** 2019-04-03 08:48 UTC
