### ISSUE TITLE
broken documentation page

### ISSUE THREAD

**Issue by jrochel** [ocsigen/lwt#268] opened 2016-08-12 15:05 UTC
https://ocsigen.org/lwt/api/Ppx_lwt yields:

> Error
> Ocaml_lexer.Error(_, _)
> Ocisgen running in debug mode

**Comment by vasilisp** [comment] 2016-08-12 15:22
Trouble with the ocsigen.org infrastructure. Until we fix it, you can look at:

https://ocsigen.org/lwt/2.5.1/api/Ppx_lwt (differs only slightly)
https://github.com/ocsigen/lwt/blob/master/ppx/ppx_lwt.mli

**Comment by Drup** [comment] 2016-08-12 15:24
(Actually, I think it's an issue with wrong markup in the file)

**Comment by aantron** [comment] 2016-09-11 21:14
Thanks. This is a duplicate of #263, though by different URL.

**Closed by aantron** 2016-09-11 21:14 UTC
