### ISSUE TITLE
Create a custom .install script for next version of lwt

### ISSUE THREAD

**Issue by andrewray** [ocsigen/lwt#404] opened 2017-06-14 08:19 UTC
Similarly to the custom META file this could be used to install things like lwt_unix in the currently expected directories, giving folk a release cycle to fix packages.

**Comment by aantron** [comment] 2017-06-14 15:29
Agreed. When notifying downstream maintainers, we will give them instructions to pin Lwt to a commit before this custom `.install` file, so they can reproduce the dependency problem.

**Comment by andrewray** [comment] 2017-06-17 15:48
Ok.  So I guess this should be the very last task done just before the next release.  Ping me when you are ready.

**Comment by aantron** [comment] 2017-06-17 16:01
I think it's fine to do it at any time – perhaps I am missing some consideration? All we should need to do immediately before release is check out the parent commit of whenever this is fixed, and use it to find wrong dependencies.

**Comment by andrewray** [comment] 2017-06-17 16:15
I was just thinking the commit that is the "one true way" should be the one directly before we add a compatibility layer, but perhaps I am over thinking it.

**Comment by aantron** [comment] 2017-06-17 16:22
I think as long as we have one commit at which we can reproduce the failure expected with new packaging, it should be fine at any time. I generally like to avoid pushing too many things to Lwt release time, because that is always a stressful process involving giant TODO lists, thinking over and over about every detail, manual testing, downloading tons of reverse dependencies, and all sorts of other tasks.

**Comment by andrewray** [comment] 2017-06-17 16:23
Fair comment.  I will have a bash at this in the next week or so then.

**Comment by aantron** [comment] 2017-06-25 17:53
I believe the code part of this is resolved by #420. I'll know to notify the maintainers, and refer to this issue, when I'm looking through the changes in preparation for 3.1.0 release. Thanks!

**Closed by aantron** 2017-06-25 17:53 UTC
Labels: medium
