### ISSUE TITLE
Version not set correctly in "lwt" version 4.2.1 (required by stog)

### ISSUE THREAD

**Issue by fccm** [ocsigen/lwt#806] opened 2020-09-12 07:17 UTC
While trying to install "stog" with opam I got an error at configure time with stog checking which version of lwt.unix is available:
```
eval $(opam env --switch 4.06.0 --set-switch)
opam install stog.0.18.0-1
# checking for lwt.unix... Package lwt.unix found with version dev, but wanted >= 2.5
```
Indeed in `~/.opam/4.06.0/lib/lwt/META` there is:
```
version = "dev"
```
When I edit this `META` file to set a correct version:
```
version = "4.2.1"
```
(and same for `package "unix"` sub-section)
Then when I run `opam install stog.0.18.0-1` the install proceeds correctly as expected.

While a release cannot be edited, it is still possible to patch the opam package.

**Comment by fccm** [comment] 2020-09-12 07:25
I'm not sure if I should fill an issue here or on opam-repo, so I filled both:

https://github.com/ocaml/opam-repository/issues/17185

please just close the one that is not appropriate.

**Comment by aantron** [comment] 2020-09-16 15:35
This is a duplicate of https://github.com/ocsigen/lwt/issues/690#issuecomment-517897278, and we addressed it for subsequent Lwt releases. Can you switch to a newer release? If not, it should be fixed by a patch in opam.

**Closed by aantron** 2020-09-16 15:35 UTC
