### ISSUE TITLE
Lwt_io sometimes register threads that do not terminate in Lwt_main.at_exit

### ISSUE THREAD

**Issue by vbmithr** [ocsigen/lwt#114] opened 2014-12-27 15:11 UTC
When calling Pervasives.exit, an Lwt program should always terminate. In some cases, it seems that the a program using Lwt_io is stuck forever, even after a Pervasives.exit.

**Comment by vouillon** [comment] 2015-01-05 12:42
This is probably a duplicate of #48

**Closed** 2016-06-27 20:46 UTC

**Comment by aantron** [comment] 2016-06-27 20:48
Indeed most likely a duplicate, but answering here since both reporters are present :) See the attached commit for an explanation of the deadlock, if you are interested. Should be fixed now.
