### ISSUE TITLE
Doc links are all pointing to 404 error pages

### ISSUE THREAD

**Issue by shinzui** [ocsigen/lwt#576] opened 2018-04-14 17:21 UTC
The README is pointing to 404 error pages, and the [manual](https://ocsigen.org/lwt/3.2.1/manual/manual) on oscigen is outdated.

**Comment by Drup** [comment] 2018-04-14 18:16
Duplicate of https://github.com/ocsigen/ocsigen.org/issues/18 . The ocsigen.org website was renovated a few days ago. This should be fixed soon.

**Comment by aantron** [comment] 2018-04-19 15:01
I believe this is fixed by @CelieArnaud in #579. At least, the links in the README and in the changelogs on the releases page seem to work.

**Comment by aantron** [comment] 2018-04-19 15:02
Correction, the 404 part is fixed. We still need to have docs for current versions of Lwt generated.

**Comment by aantron** [comment] 2018-04-25 16:08
The first result in Google (and Bing) searches for "Lwt API" points to https://ocsigen.org/lwt/api/, which is now dead (404). cc @balat @CelieArnaud

**Comment by aantron** [comment] 2019-04-03 09:04
This has indeed been fixed.

**Closed by aantron** 2019-04-03 09:04 UTC
